de1beta/gui.tcl

Fixed extent of listbox scrollbars

---

de1plus/bluetooth.tcl
de1plus/machine.tcl

bluetooth: Add Hiroia Jimmy scale

---

de1plus/skins/default/de1_skin_settings.tcl

Fix for #1 where some scrollbars did not go from zero to one.

Fixed list box scroll bar ranges

---

de1plus/utils.tcl

Show android toast on splash screen resize, fixes #35

---

de1plus/plugins/visualizer_upload/plugin.tcl

I fixed this plugin to properly follow the multipart/form-data protocol. Tested locally and confirmed it works.

Fixing Visualizer plugin for proper upload.

---

de1plus/misc.tcl

Add visualizer upload to tracked files

---

.gitmodules
de1plus/misc.tcl

Add Iconik Skin as a git submodule and link in the current master

---

de1plus/gui.tcl
de1plus/skins/default/de1_skin_settings.tcl
de1plus/vars.tcl

In this commit we are fixing the plugin loading order as well as making accessing the
settings menu easier.

plugins: Add toggle buttons

---

de1plus/bluetooth.tcl

Assume BLE names to start with the respective identifiers, over just containing them

---

de1plus/device_scale.tcl

Changes to the approach to managing scales resulted in entering HotWater
not always providing a tare function at its start. Restore that behavior.
Retain the existing "keep scale near zero" behavior for auto-tare states.
Explicitly tare the scale on entering HotWater mode, but only if not within
$::device::scale::tare_threshold as certain scales beep on tare
SIGNIFICANT END-USER CHANGES
============================
Scale should once again auto-tare at the beginning of HotWater
(assuming no plugin or scale overrides)

scale: Ensure tare on start of Hotwater

---

documentation/de1_app_plugin_development_overview.md

Documented my findings based on reading the source.

Add first pass at plugin documentation

---

de1plus/de1_comms.tcl

Users have reported unresponsive BLE after interacting with profiles.
In one case, a queue depth of over 1300 was observed. Examination
of logs suggested that at least one cause was users updating profiles
and settings faster than they could be transferred to the DE1.
As the settings that may be pending in the BLE queue are about to be
overwrtten, remove "matching" entries prior to adding their replacements.
remove_matching_ble_queue_entries {comment_regexp} is used to match
against the "comment" that is provided to userdata_append
This is a "spot fix" and should be reexamined if the BLE queue
is rewritten in the future. The following calls are addressed:
* de1_send_shot_frames
* de1_send_steam_hotwater_setting
* set_steam_flow
* set_steam_highflow_start
* set_tank_temperature_threshold …

Remove "stale" profile and settings requests from BLE queue

---

de1plus/history_viewer.tcl
de1plus/shot.tcl

Load shotfiles for history viewer asynchronous

---

de1plus/dui.tcl

Hide the keyboard on canvas focus instead hiding it and trying to '1'

---

de1plus/misc.tcl

Added the new file from PR #145 to misc.tcl so it's included in the nightly distribution

New file to distribute skins/MimojaCafe/theme.tcl

---

de1plus/plugins/visualizer_upload/plugin.tcl

No runtime errors if the zint package (for generating QR codes, available in Androwish distributions) is not available in the target system. The situation is warned about in the log, the space for the QR code is left blank, and the browse button does not mention the QR code.

Avoid errors in visualizer_upload if the zint package is not available

---

de1plus/bluetooth.tcl
de1plus/machine.tcl
de1plus/vars.tcl

This is primarly to keep track of any issues during testing

Add MEATER support

---

de1plus/profile.tcl

Now correctly handles the case of per-step temperature of basic profiles:
- A new item added to step 0 of the returned dictionary, with key `temp_steps`, when per-step temperatures are enabled
- Hide the `preinfusion temp boost` step in this case, and re-add the 2-seconds adjustment to the preinfusion step

Per-step temperatures in profile::legacy_to_textual

---

de1plus/plugins/visualizer_upload/plugin.tcl

**Changes in the `visualizer_upload` plugin:** 
Downloading of profiles from Visualizer has been moved from the `download` command into its own command `download_profile`. So that it can be called independently without downloading the rest of the shot, as for recently downloaded shots the base shot data has already been downloaded in the list.

Move profile downloading into its own proc download_profile

---

de1plus/bluetooth.tcl
de1plus/device_scale.tcl
de1plus/machine.tcl

This allows the usage of the Reflex Smartchef scale. It is available online for around 25$
Unfortunately there is no software-triggered taring. So the button needs to be pressed.

Added basic smartchef scale support

---

de1plus/plugins/visualizer_upload/plugin.tcl

- maxAttempts of 4 (3 retries instead of 2)
- exponential backoff (1. retry after 150ms, 2. after additional 300ms, 3. after additional 600ms)
- last error is stored and visible in settings as it was in original version
- Increased plugin version to 1.3

3 retries instead of 2, exponential backoff and last error in settings

---

de1plus/bluetooth.tcl

Reverts decentespresso/de1app#307

Revert "scale, bookoo: Cleanup the code and add battery and flow parsing"

---

de1plus/bluetooth.tcl

There is an issue or intended behaviour that the scale will sometimes not register the initial messages. This is due to the unacknoledged nature of writes which acaia chose for their products. So we just repeat the startup sequence until the scale plays nice...
PR Note: This was _not_ tested on any teclast tablets but only on samsung tablets!

bluetooth/acaia: yell the identification until the scale talks to us!

---

.gitmodules

A_Flow is profile plugin based on D-Flow. It's a mix of D-Flow and Adaptive (for medium roasts) profile plus some adaptions.
I'm using it since beginning of the year and want to share it now.

Add A_Flow plugin

---

de1plus/bluetooth.tcl

Not sure if this will fix my issue, but reviewing the code and this looks just wrong.

Attempt to fix 328. Fix apparent bug on enabling bookoo weight notifications
