- de1beta/create_de1_update_icon.tcl
- de1beta/gui.tcl
So far the path to the de1app sourcefolder had to be placed directly under /sdcard.
This leads to the de1app repository beeing not directly executable. While the app would run
the icon creation would not.
To fix that we are querring the current scripts folder to find the correct path from there.
> gui: Make app icon creation folder independant

- .gitignore
- build-beta-release.sh
- de1plus/de1plus.tcl
- de1plus/misc.tcl
- de1plus/version.tcl
To be able to change the version easily programmatically we are moving the version
definition to its own minimal version.tcl file.
So far the version was defined in the de1plus.tcl where there are many things that could
break when changed automatically.
> misc: Move version to version.tcl

- de1plus/machine.tcl
We are seeing customers turning off their machines over night, not trusting the
power usage. To accomodate for their usecase we are disabeling the screenlock if
requested.
> machine: add hidden setting to lock the screen if wanted

- de1plus/gui.tcl
- de1plus/plugins.tcl
- de1plus/plugins/example/plugin.tcl
- de1plus/plugins/visualizer_upload/plugin.tcl
- de1plus/plugins/web_api/settings.tdb
- de1plus/skins/Insight/skin.tcl
- de1plus/skins/default/de1_skin_settings.tcl
- de1plus/vars.tcl
As we do not want to source and extension code without the
uses consent we can not display any dynamic variables.
But: We can use the additional space to show the saved settings
that are in use. This allows us to double-check the current configuration
before activating a plugin. We can not easily open the settings file
in an external android editor without the risk of exposing user data to
3rd party apps without the user consent. I personally dont think we can
solve that from within the app (for now). User will still need to edit their
plugin settings from within the filebrowser / adc / their app of choice.
> Print settings when selecting an extension

- de1plus/binary.tcl
- de1plus/vars.tcl
Add additional variables to espresso log files
As we are no longer just using the App to save, edit and view the shot files
it is time to add the missing variables to shot files.
This includes in this commit:
- step transitions
- resistance
- deltas
As the App might change the way it is calculating things in the future it
is unrealistic for 3rd party devs to reimplement and keep up with all changes.
To easy traceability a app_version field was added on the highest shot file level.
PLEASE MERGE #53 first
> Shot file improvements

- de1plus/binary.tcl
The $::previous_FrameNumber gets initialized with -1 instead of 0.
Therefore checking for 0 as unitialized state is not providing the
expected results leading to the first state change line not beeing drawn.
This commit fixes this behaviour by changing the check.
> binary: Draw first state change

- de1plus/skins/Insight/skin.tcl
It seems like the basic and advanced profiles should display weight in the same way, i.e., display the final (saved) weight when not running.
> Fix idle scale weight for basic profiles

- de1plus/plugins.tcl
- de1plus/plugins/example/plugin.tcl
- de1plus/plugins/visualizer_upload/plugin.tcl
- de1plus/vars.tcl
This PR fixes a number of things in the extensions system:
- To manage dependencies between plugins, a plugin may need to force preloading or loading another plugin. In this case, we must ensure that plugins are not preloaded nor loaded more than once. To handle this, I have added variable "plugin_preloaded" in the plugin namespace. "plugin_loaded" already existed but was set after preloading, not after loading. Now both are set in the right places and they are checked before either preloading or loading. NOTE that for loading this does the same as my previous PR (which used a global variable), but this is a better system that should overwrite the previous suggestion.
- Added new utility procs "plugin_available", "plugin_preloaded" and "plugin_loaded".
- Plugins can set the new namespace …
> Changes in extensions UI. Handle plugins dependence.

- de1plus/vars.tcl
The recently introduced field "beverage_type" was not being properly reset. Because it's a new field that is not set in the GUI, existing user-created profiles usually don't have yet included it. Because everything goes to the settings and persists there forever if not changed (something that produces problems in sooo many ways), this was getting wrong values when a profile was selected that hadn't that field defined.
To reproduce:
- Make a shot using the profile "Forward flush". This modifies the settings with ``beverage_type cleaning``
- Change the profile to a user-created profile that hasn't the field "beverage_type" defined in the <profile>.tcl file
- Make a shot with the new profile.
- The new shot file gets ``beverage_type cleaning`` despite being e.g. an espresso shot.
The field …
> Properly reset beverage_type to not persist if undef in new profile

- de1plus/skins/Insight/skin.tcl
Having names for the graphs will allow extensions to be able to
modify them, such as hiding elements, changing data sources,
or changing styling.
::skin::insight::graph::pressure
::skin::insight::graph::flow
::skin::insight::graph::temperature
::skin::insight::graph::combined_zoomed
::skin::insight::graph::temperature_zoomed
::skin::insight::graph::steam
::skin::insight::graph::steam_done
::skin::insight::graph::steam_done_zoomed
::skin::insight::graph::steam_done_temperature_zoomed
::skin::insight::graph::steam_zoomed
::skin::insight::graph::steam_temperature_zoomed
> skin: Insight: Name ::blt::graph widgets for use by extensions

- de1plus/bluetooth.tcl
As commented on issue #76, I have removed the duplicated version of the fast_write_open proc in bluetooth.tcl (which was the one actually being called when settings were saved), and keep the version on updater.tcl. 
I've had it like that on my dev environment & tablet for a few days without issues, and it has solved the bug of duplicated line endings in settings file on every save under Windows. The differences between the 2 versions were:
- The bluetooth version did not have error catching
- The bluetooth version was non blocking, but as the comment in the code says, apparently it's not needed
- The bluetooth version didn't have end-of-line conversion, which is needed to solve the bug on Windows.
> Remove duplicated fast_write_open

- de1plus/de1_de1.tcl
Resolves a start-up issue when $::settings(line_frequency)
does not exist or evaluates to False.
> de1: Fix first-time initialization of line frequency

- de1plus/machine.tcl
After noting that substate 14 was returned with FW 1238 and that `::de1_substate_types()` did not include it, complete the state and substate lists to be consistent with APIDataTypes.hpp
Based on APIDataTypes.hpp
> machine: Complete state and substate arrays

- de1plus/de1_de1.tcl
- de1plus/machine.tcl
Although HotWater was listed as a tracking state for SAV,
the pour_volume wasn't being set for HotWater.
Reetting of ::de1(pour_volume) is in machine.tcl
consistent with other flow-start initialization
to keep them together in one place for clarity.
Suggest future refactor out of ::reset_gui_starting_*
An unwrapping issue related to the DE1 ShotSample timer
was also corrected. This event occurs roughly every
9 or 11 minutes and would result in "missing" one update,
on the order of 1 ml or less, if it occurred during flow.
SIGNIFICANT END-USER CHANGES
============================
SAV should be usable for hot water, with or without a scale.
> de1: Provide SAV for Hot Water

- de1plus/unde1plus.sh
Change working directory into the de1plus directory as the first part of the
script so that relative paths to *.tcl files work correctly.
> Allow de1plus/unde1plus.sh to be launched from anywhere

- de1plus/vars.tcl
If a shot was interrupted during PreInfuse, the next shot would render
negative time in the GUI until the shot ended. Once that next shot ended,
the times rendered would be correct.
Traced to ::start_espresso_timers not properly resetting the timers.
Resolved by resetting those timers in that routine, presently in vars.tcl
There still is a behavior where, before flow begins, the times from
the previous shot appear. Changing this would mean that an "aborted"
shot would wipe the previous timers. Deferring any such changes to next
release cycle.
> de1: Fix "negative time" display during some shots

- de1plus/binary.tcl
- de1plus/de1_de1.tcl
Commit 94a0ed00 introduced a case where the after_flow_complete event
was being triggered twice under certain circumstances. This commit
resolves this by checking that there is not a pending timer before
triggering the event.
> de1: Remove duplication of after_flow_complete trigger

- de1plus/machine.tcl
Firmware 1255 and later may utilize SchedIdle (21, 0x15)
state as a request and in its reports.
Extend the ::de1_state array to accomodate.
::de1_num_state already includes an entry.
> de1: Add SchedIdle to ::de1_state array

- de1plus/vars.tcl
The scale's timer is now managed on events. Remove the now-redundant,
hard-coded calls to start and stop it in vars.tcl.
Felicita scales are presently the only scales with a visible timer.
> scale: Remove redundant timer requests from vars.tcl

- de1plus/gui.tcl
This should solve a long-time bug that made that pages that were added "late" (i.e. not during startup) didn't have their canvas items correctly hidden. It was also not hidden the visualizer_upload setting page controls when leaving the page after recent changes on the plugin.
The reason is that the global variable used to know which labels to hide was $::all_labels, and it was being constructed in proc page_display_change only ONCE, and never updated. So, after page_display_change was run once, new pages (or new items added to existing pages) were not shown correctly but not hidden properly.
Updating $::all_labels on every page_display_change slows down things, so to solve this I've completely ditched the $::all_labels system, and used instead the solution I'm applying on the forthcoming …
> Solve bug with $::all_labels in proc page_display_change

- de1plus/vars.tcl
The .shot file presently only contains a timestamp in seconds without
timezone.  Uploaded .shot files, such as from an extension, may no
longer have their name to assist in cross-referencing with the logs.
Add local_time as the line after "clock" at the top of the .shot file.
> Add local_time to .shot file

- de1plus/logging.tcl
_**Checked against app, needs to be checked against build environment there**_
As a result of inclusion by other packages, logging is initalized
during the build process. Console logging bleeds into the build logs.
To disable logging, set to Boolean True externally, prior to any
`package require` of de1app code. One way to do this would be:
namespace eval ::logging { variable disable_logging_for_build True }
> logging: Disable logging when used during build

- de1plus/vars.tcl
_**Waiting for feedback from impacted user(s). Thread on DD open.**_
_No negative feedback received. Opening for adoption._
_**Testing with any forthcoming scales prior to merge would also be valuable.**_ (Hint: @decentjohn )
_These changes can be tested out on "any" current build with the plugin available on that thread._
Scales that have a timer and have ::device::scale::use_timer True
will have their timer reset on entering a flow state, such as Espresso.
Code in vars.tcl would also call ::scale_timer_reset on resetting the
espresso timers, typically at the start of flow.
At the start of flow, a timer-start command is sent. This often
immediately after the timer-clear command from vars.tcl. There is some
evidence that scale hardware may not gracefully handle tight timing.
Rather than …
> scale: Remove redundant scale-timer reset from vars.tcl

- de1plus/gui.tcl
- documentation/de1_app_core_shot_cycle_overview.md
As per discussion with @decentjohn 
Change the default implementation of
::gui::notify::scale_event record_complete
to be "Shot complete" for those skins that do not override it.
Adjust documentation to reflect the change.
> gui: Revise wording on after_flow_complete to "Shot complete"

- de1plus/de1_de1.tcl
A newly connected DE1 may not yet have been queried for its line
voltage when frequency estimation begins. Although
::settings(heater_voltage) exists, it may be an empty string.
Resolve by returning False as is already the case when undefined.
Note the Tcl inconsistency behing the logic:
% set n ""
% string is double $n
1
% expr { double($n) }
expected floating-point number but got ""
> de1: Handle heater voltage being an empty string

- de1plus/plugins/web_api/plugin.tcl
**This is not a priority for v1.35**
As noted in #73 the web_api plugin previously created and used the `::wibble` namespace, even if the plugin was not enabled. Resolved by moving the `proc ::wibble::*` definitions into `main {}`
Seeing duplication of the generation the response object and expecting to add to the API, made generalized "200"  returns for JSON and text data.
In resolving that, noted that the port was hard-coded.
Added a /flush action, which calls `::logging::flush_log` (Introduced by #114, not merged at this time).
> Improve web_api plugin

- de1plus/gui.tcl
User reported that every 30 seconds, evne when sleeping, the toast
"Warning: Scale not connected" is displayed, along with a ticking sound.
This can be replicated by configuring a scale, turning it off, and setting
automatically_ble_reconnect_forever_to_scale 1
It is due to the `ble` stack sending a connection event as it starts
to try to connenct by address and then a disconnect event when it fails.
Gate the message so it is not displayed when the DE1 is in Sleep
state.
Long-term resolution is a BLE stack that properly reports
connection state.
Resolves https://github.com/decentespresso/de1app/issues/129
> gui: Suppress scale disconnect messages when DE1 is in Sleep

- de1plus/main.tcl
Multiple users have reported instability when running AndroWish 2020-11-05
("The Flux Capacitor").
Log the tcl patch level and warn if 8.6.10, corresponding to AndroWish 2020,
along with a recommendation to use the 2019 version.
> app: Log tcl_patchLevel, warn if running 8.6.10 (AndroWish 2020)

- de1plus/shot.tcl
Typos in commit 3998a050f resulted in errors.
Corrected spelling of "translate" and "borg"
> shot: Fix misspelling of "translate"

- de1plus/dui.tcl
- de1plus/utils.tcl
This should correct the problems in the build server, as there $::android==0 and $::undroid==0
> Initialized font vars when android=0 & undroid=0

- de1plus/history_viewer.tcl
The history viewer setup method was resetting the current theme to the default one and not setting it back, whereas it should not touch the theme.
This was copied from the pages integrated in DUI like dui_number_editor, that change temporarilly the theme to default for setting up the page because they must match the aspect of the settings pages (default/Insight) and then set it back to the current skin theme at the end, but it is not needed in history_viewer, which must rather integrate with the skin theme. This had the side effect of altering how some plugin pages rendered under skins different than Insight.
> Don't change the theme in history viewer

- de1plus/bluetooth.tcl
**I do not have an Acaia scale so I can not test this code path.**
_While believed correct, confirmation would be appreciated._
Add missing line-continuation \ for non-Skale path.
> bluetooth: Resolve Error: invalid command name "2a80"

- de1plus/dui.tcl
- de1plus/utils.tcl
Image commands in DUI are now grouped under the subensemble namespace 'dui image':
- New commands 'dui image dirs', 'dui image add_dirs', 'dui image add', 'dui image find' and 'dui image photoscale'
- Resize images dynamically if needed on 'dui add image'
- De-hardcode the base screen size 2560x1800 everywhere.
- When resizing PNG files, now transparent background is preserved.
- Don't fail if an image file is not found, just warn in the log.
In addition, I made the following changes:
- Add DUI & platform data to the log on init to facilitate debugging.
- Fix bug introduced by first version of DUI, which was storing in the settings the variable "screen_size_height)"
- Make sound_name in 'dui say' optional.
-
> New dui subensemble 'dui image'

- de1plus/dui.tcl
- de1plus/history_viewer.tcl
- documentation/decent_user_interface.md
This styles all visual items in the new history viewer using DUI, so its aspect now adapts to the skin in use (if the skin provides its own DUI theme). Defining a general DUI skin theme should be enough to get the History Viewer to match the visual aspect of the skin, but further customization can be done modifying the desired aspects of the "hv_*" styles for the skin theme (hv_button, hv_done_button, hv_graph, etc.)
Several changes were done in DUI itself to allow this styling:
- dui::add:listbox gets a new -select_cmd option to set the callback to run when an item is selected in the listbox. No need to bind it manually now.
- dui::aspect::list gets a new -as_option option that allows to return a list of aspects to be used directly in a widget creation or configuration call. Useful to …
> Theme new history viewer. Get DUI to style graphs

- de1plus/dui.tcl
- documentation/decent_user_interface.md
Improve the page lifecycle management possibilites of DUI:
- Pages can be deleted with 'dui page delete'
- Pages with an associated namespace can be totally recreated with a different theme with 'dui page retheme'
- New 'dui page' commands to query the lifecycle state of the page: 'dui page is_loaded', 'dui page is_drawn' and 'dui page visible'
- New 'dui page' commands to list all canvas items in the page (dui page items) or confirm is a tag exists in the page (dui page has_item)
- New event 'setup' allows to set setup actions with 'dui page add_action <page> setup'
- Page namespaces can now define an 'update_vars' command to run whenever its onscreen variables are updated
- Documentation updated to describe the new commands and page lifecycle. Also added several missing API commands …
> Improve DUI page lifecycle management

- de1plus/de1_comms.tcl
commit 69f8968a provided functionality that prunes settings and shot
data that is about to be overwritten from the BLE queue.
Now that this seems stable and reliable, only log when items are
removed, omitting the "ble_queue: No stale '%s' on queue; %d"
message at DEBUG level.
> de1_comms: Don't log when no "stale" items were pruned

- .gitignore
- de1plus/de1app.tcl
- de1plus/misc.tcl
Ref: https://github.com/decentespresso/de1plus_misc/pull/2
_**This should get a version version bump for `de1app.tcl` and be reflected in `skins/default/de1_skin_settings.tcl`**_
Read in the build-info file if present, log it at the top of the log (so logs uploaded always have detailed app-version information).
Provide programmatic access to the build-info contents.
~~Use the more-detailed string in the GUI~~
**No GUI changes**
> Utilize the build-info file in the app

- de1plus/de1_de1.tcl
- de1plus/pkgIndex.tcl
Although the flow rate and timing is already available in the
event_dict for on_shotvalue_available, this is a common-enough
value needed by the GUI and shot-control extensions to have it
available in the event_dict directly.
Added "volume_dispensed" to the event_dict as the total of
$::de1(preinfusion_volume)
$::de1(pour_volume)
Frame information is available to consumers in the same event_dict
so that division by flow-phase, frame, or time, is possible.
Package version bump due to additive API change.
> de1: Add volume_dispensed to on_shotvalue_available

- de1plus/app_metadata.tcl
- de1plus/metadata.tcl
- de1plus/misc.tcl
- de1plus/pkgIndex.tcl
- de1plus/utils.tcl
An initial simple implementation of a metadata package as described [on Basecamp](https://3.basecamp.com/3671212/buckets/7351439/messages/3762617806):
Having a data dictionary for the application fields in place should help in several ways:
- **Avoid code repetition**. Many values, such as lower and upper limits for variables, are currently hardcoded in many places in the code, which leads to problems (how often we've seen "probably that bug is due to a GUI control somewhere setting a limit on the variable, which is constraining it everywhere"?). Having a standard way to retrieve those values should help mitigate the problem. And anything that avoids code repetitition ("copy & paste") helps code maintenance.
- **Provide a standard way to add new fields**. Adding new data has proved to be …
> Metadata package 

- de1plus/app_metadata.tcl
- de1plus/dui.tcl
- de1plus/gui.tcl
- de1plus/history_viewer.tcl
- de1plus/utils.tcl
- documentation/decent_user_interface.md
- Adds new command 'add dui text' for adding Tk text widgets.
- Renames 'add dui text' to 'add dui dtext'. This is done for consistency of the API, as whenever a Tk widget exists 'dui add <widget_type>' is the command to add it, and 'dui add d<widget_type>' is the canvas-based DUI version. 
- Fixes an error in the vertical scrolling of Tk text and multineline_entries
- Commands translate_coordinate_finger_down_x, translate_coordinate_finger_down_x and is_fast_double_tap moved to DUI.
> Add DUI support for tk text widget

- de1plus/dui.tcl
Fixes the bug found by @damian-au that font directories paths added with 'dui font add_dir' failed to be added correctly if the path contained spaces. Same happened with image folders added with 'dui image add_dir'.
> Fix empty spaces bug in DUI fonts or images folders

- de1plus/bluetooth.tcl
- de1plus/machine.tcl
- de1plus/skins/default/de1_skin_settings.tcl
- de1plus/vars.tcl
> Add MEATER support

- de1plus/app_metadata.tcl
- de1plus/dui.tcl
- de1plus/machine.tcl
- de1plus/metadata.tcl
- de1plus/utils.tcl
- documentation/decent_user_interface.md
This adds several new features to both the DUI and Metadata packages, many of them in preparation for DYE v3:
**Metadata:**
- New `metadata::set` command to modify existing metadata 
- New argument `after` for command `metadata:add`, to allow adding fields in the desired order.
- drink_ey gets new upper limit 'max' and new 'default', as it incorrectly had those of TDS
- If a new dictionary property is added, it is added to all existing fields, with empty string as default value.
- Add scentone field
**DUI:**
- New command `dui::item::moveto` allows to move visual items, and specially compounds, at once, to a new screen position.
- All 3 forms of load page actions now can modify the page being loaded (before only the namespace load command could do it)
- Add validation of fields with …
> Dui and Metadata updates

- de1plus/app_metadata.tcl
- de1plus/skins/Insight/scentone.tcl
This increases the upper limit for the drink_tds shot variable from 14 to 25%, as requested by some users. Seems that strong ristrettos can achieve values around 20%, so 25% seems a safe upper limit.
This required changing the limit in the scale widget of the "scentone" file, as it bounds to $::settings(drink_tds) and higher values are auto-set to the upper limit due to this binding. Also modified in the new app metadata. I've done the same change in SDB so that it's also acknowledged in DYE.
> Increase drink_tds upper limit from 14 to 25

- de1plus/app_metadata.tcl
- de1plus/dui.tcl
2 minor changes:
- New 'source' property in the metadata dictionary allows to distinguish those fields that are defined by the user (like shot description fields) from those defined by the machine ('app') and those that are derived ('calc').
- Correct bug in dui::item::moveto that was not rescaling coordinates
> New metadata 'source' property. dui::item::moveto rescales coordinates

- de1plus/dui.tcl
- documentation/decent_user_interface.md
This allows to query and modify the initial state of page items at runtime. Previously this could only be defined at setup time (when the item was added to a canvas page). Answers a request from @Damian-AU
> Query or change -initial_state with dui::item::cget & dui::item::config

- de1plus/plugins/visualizer_upload/plugin.tcl
Here is a small fix for preventing the visualizer upload plugin from running after HotWater and HotWaterRinse operations.  This will gate the subsequent upload function to execute only when previous state is Espresso.
> Potential fix for issue #164.   Upload data only for espresso operations in visualizer_upload plugin

- de1plus/app_metadata.tcl
- de1plus/dui.tcl
- de1plus/utils.tcl
- documentation/decent_user_interface.md
This PR includes several improvements in **DUI**:
- Images are now always cached, so adding the same image several times will only load it once, and will be reused for all canvas images that use it (request from @decentjohn)
- Image loading can now be delayed until a page that contains the image is shown for the first time. This is enabled by setting the new DUI configuration variable 'preload_images' to 0. This setting is initialized by default to the value of the global DE1 setting 'preload_all_page_images' (request from @decentjohn)
- A new "oval" shape for dbuttons, to create circle or oval-shaped buttons (request from @decentjohn)
- Page dui_item_selector now works properly when it is setup to accept multiple items selection.
And one minor change in **metadata**:
- bean_brand and …
> DUI image caching & delayed load; oval dbuttons; multiple select in dui_item_selector

- de1plus/dui.tcl
This fixes a bug [reported](https://3.basecamp.com/3671212/buckets/7351439/messages/3803211859#__recording_3847087994) by @Damian-AU that the -image option in dui::add::dbutton was not working correctly.
While fixing this I found another bug, that relative image paths were not being preserved when the image is automatically resized to a new screen resolution if the image is in a subfolder of a <screen_size_width>x<screen_size_height> folder. This has been fixed and now the new resized image is created in the same relative subfolder of the new resolution.
> DUI: Fix -image option for dui::add::dbutton and relative paths in images resizing

- de1plus/vars.tcl
Users have difficulty managing profile files as they are named with timestamps that don’t give a clue to their contents.
Modified save_profile to use a name derived from the profile_title. Name
made “safe” by replacing whitespace with underscores, changing / to a
doubled underscore, and removing other potentially unsafe symbols and
unicode control characters
Signed-Off-By: Joe Duncan <j@josephd.net>
> profiles: File name reflects profile name

- de1plus/device_scale.tcl
- de1plus/machine.tcl
- de1plus/vars.tcl
- documentation/de1_app_core_shot_cycle_overview.md
**Motivation**
Commit b619ebf5 extended the usage of **$::settings(drink_weight)** to store the weight of the last espresso shot **or the last hot water shot**. Previously that field was used only for espresso shots.
The problem is that `$::settings(drink_weight)` was also being used forshot metadata. End users could modify `$::settings(drink_weight)` after the shot, either in Insight ("My espresso" tab in the Godshots page) or using the DYE plugin. The field was also being stored in the SDB database, and in visualizer.coffee. 
After the change, if a user pours hot water after making a shot, the weight of the hot water is saved on `$::settings(drink_weight)`, overwritting the weight of the last espresso. If now the user tries to edit his last espresso shot, re-upload it to Visualizer, …
> Make settings(drink_weight) store espresso weight only (not hot water)

- de1plus/dui.tcl
- documentation/decent_user_interface.md
Coming from a [suggestion](https://3.basecamp.com/3671212/buckets/7351439/messages/3803211859#__recording_3859770360) by @decentjohn, `dui::item::show`, `dui::item::hide` and `dui::item::show_or_hide` now support
named options `-current` and `-initial`. Also the previous positional argument `check_page` is now a named option `-check_page`.
A helper command has also been introduced, `dui::item::pages` , that returns a list with all the pages in which the specified item or widget appears.
Update the documentation, including better explanations for `dui::add:graph` as suggested by @Damian-AU.
> Change initial show/hide state with dui::item::show_or_hide

- de1plus/dui.tcl
Corrects a bug in DUI introduced by PR #171, that is constantly showing runtime error "list must have an even number of elements".
> Correct "list must have an even number of elements" in nightly 1.36.5.65

- de1plus/dui.tcl
- de1plus/gui.tcl
- de1plus/utils.tcl
- documentation/decent_user_interface.md
This brings 2 main updates to DUI:
1. The "clickable" area of the dropdown arrow of dcomboboxes was too small and often several touches were needed. It has been modified to be a dbutton with a bigger clickable area. This change needs matching updates in both DYE & MimojaCafe.
2. DUI auxiliar pages "dui_number_editor" and "dui_item_selector" now can be rethemed on the fly by passing a named argument -theme to the "dui page load" command. This is used to adapt its aspect to the page that opens them.
Other minor changes:
- dui::page::theme gets a new argument 'default'.
- dui::page::retheme now validates new_theme and logs invalid themes.
- Styles of buttons in dui_number_editor are now moved to the global theme.
- dui::item::relocate_text_wrt now can work with items different that text
> Increase tapping area of dcombobox dropdown. DUI pages adapt to theme

- de1plus/dui.tcl
An error introduced by PR #174 was being raised as soon as the app was started on non-Insight skins.
dui::page::add_items had wrongly stopped being exported, now exported again.
> Re-export dui::page::add_items

- de1plus/utils.tcl
"Artistic" skins like 1960's were showing the default skind background page images instead of their own images, as [reported](https://github.com/decentespresso/de1app/commit/8759bbff46cfb3ff93e41428d23896153f446352#commitcomment-52736923) by @decentjohn. 
The reason was that if the same image file was found by DUI in both the current skin and the default skin, the default one took precedence because the default folder was first in the image search path list. So now the default image folder is added to the search path list _after_ the skin images folder.
> Add DUI default skin image folder after the current skin image folder

- de1plus/dui.tcl
According to [this message](https://3.basecamp.com/3671212/buckets/7351439/messages/3803211859#__recording_3904677232) from @decentjohn, the lines and arcs in rounded rectangle outlines could be one pixel off (probably not showing on standard P80x tablet due to resolution & dithering). So one pixel has been added to the endings of the 4 lines and 4 arcs that compose the button outline.
> Incr 1px on ends of lines&arcs in dui::item::rounded_rectangle_outline

- de1plus/dui.tcl
This fixes the bug [reported](https://3.basecamp.com/3671212/buckets/7351439/messages/3762831315#__recording_3963190216) by @Damian-AU that the arc on the botton-right corner of DUI dbuttons with `-shape outline` was not being correctly drawn. This was due to an offset that had to be -1 instead of +1.
> Fix bug drawing bottom-right arc of outline dbuttons

- de1plus/dui.tcl
- documentation/decent_user_interface.md
This PR completes the DUI version of scales, called "dscales". They offer an alternative to Tk scale widgets, built from canvas primitives. Previous versions of "dscale" worked on PC but failed on android. Now they should work on all platforms, plus several improvements have been made to make the `-resolution` option work correctly for setting discrete values.
A new command `dui platform button_motion` has been introduced, that, similar to analougosly named commands, returns the virtual event corresponding to button or finger motions depending on the current platform.
To reviewers: there is no code currently in the app that shows a "dscale", so it can be tested. To test it, I suggest to manually replace line  1102 in file `skins/Insight/skin.tcl`:
```tcl
add_de1_widget "steam steam_1 …
```
> Make DUI dscales work on tablets

- de1plus/skins/Insight/skin.tcl
Changes the steam max flow rate scale widget in Insight steam page from a Tk scale to a DUI dscale, as [requested](https://github.com/decentespresso/de1app/pull/184#issuecomment-882183053) by @decentjohn.
> Changes the steam max flow rate scale widget to a DUI dscale

- .gitmodules
Pretty simple plugin to restore the previous LCD scale functionality that were changed in 64ab57cca3aa1111e429b02cb18b5eaa096603f9. 
It was tested both on desktop (macOS) and on a tablet and seemed to have no issues.
> Added plugin for old_lcd_disable

- de1plus/dui.tcl
- de1plus/history_viewer.tcl
- documentation/decent_user_interface.md
This DUI update introduces "dialog" pages, as discussed on the [DUI dialogs](https://3.basecamp.com/3671212/buckets/7351439/messages/4137556613) thread in Diaspora.
`dui::page::add` now allows pages to have a type. Old/standard pages get the type "default" by default, and 2 new types of pages are introduced: "**dialog**" and "**fpdialog**".
- Pages of both "dialog" and "fpdialog" have DUI keeping a stack of open dialogs, so that control can be automatically returned to the page that opened the dialog. A return callback can be used to process the answer from the dialog.
- "fpdialog" are "Full Page Dialogs", and, like "default" pages, they occupy the whole screen
- "dialog" pages only occupy a part of the screen, and are open on top of the page that opens them. The page that opens them is …
> DUI dialogs

- de1plus/plugins/visualizer_upload/plugin.tcl
Changes to the visualizer_upload extension: CC @miharekar
- Make visualizer settings page a DUI namespace page:
- Changes the page name to just "visualizer_settings" 
- Set type=fpdialog, so it can be invoked from any page using dui::page::open_dialog, and control is returned to the page than opened it when the "Ok" button is clicked
- Uses a DUI dcheckbox instead of a Tk checkbox for "Auto-upload"
- Reformat the "Last upload" area to leave place for the new QR code
- "Last upload" section now shows either "Last upload" or "Last download" and its result, depending of which was the last action.
- "Browse this shot" is now a dbutton for opening in the system browser, and a QR code is shown with the link.
The extension now supports downloading shots from Visualizer in addition to uploading. …
> Visualizer upload 1.1: DUI settings page, downloads & QR

- de1plus/app_metadata.tcl
- de1plus/dui.tcl
This fixes a couple of minor bugs in DUI and metadata, plus adds some features needed in the new version of DYE:
- New commands dui::page::width, dui::page::height and dui::page::split_space
- Now DUI dialogs can be closed by tapping anywhere in the background page (except on Tk widgets, as these are always highest on the z-order stack)
- Change some default theme aspects for the new dialogs and "menu dialogs".
- Make dui::item::enable, dui::item::disable and dui::item::enable_or_disable work correctly on Tk widgets (previously they worked only with canvas items)
- Now only pages of type "dialog" are explicitly rethemed in dui::page::open_dialog, pages of type "fpdialog" are not, as this produced pages using aspects from mixed themes in some cases.
- App metadata: Make fields …
> DUI & Metadata update

- de1plus/app_metadata.tcl
Settings variable `grinder_dose_weight` is  defined again as a propagated field in metadata. This was changed in commit c5c3b12 and had the side effect of resetting the dose in the home page of the MimojaCafe skin every time a shot was started, so it has been reverted to `propagate=0`.
> Reset propagation of grinder_dose_weight

- de1plus/dui.tcl
A recent commit adding multi-radius to DUI dbuttons (different radius per corner) was using `::tcl::mathfunc::max`, which was not available in the earlier versions of Androwish used in the very first tablets that came with the first DE1s. This is probably the reason that recent nightlies were crashing the app on startup seemingly at random: because it only affected users with older versions of Androwish.
So I've added our own `max` function and replaced calls to `::tcl::matchfunc::max` by calls to `::max`, and verified that it works both under "The Leyden Jar" and "Eppur si Muove" Androwish distributions.
> Replace ::mathfunc::max by our own version that works in older Androwish

- de1plus/dui.tcl
- documentation/decent_user_interface.md
- Introduce 2 new DUI controls, "dselector" and "dtoggle", described in [this Diaspora thread](https://3.basecamp.com/3671212/buckets/7351439/messages/4304368091):
- 2 new exported commands `dui::add::dselector`  and `dui::add::dtoggle` 
- 4 new non-exported commands `dui::item::dselector_click`, `dui::item::dselector_draw`, `dui::item::dtoggle_click`, and `dui::item::dtoggle_draw`
- Each arc & line of dbuttons/shapes outlines get its own tag, so they can be colored or modified independently (which is used by the dselector widget)
- New utility commands `lsequence` and `min`
> New DUI widgets dselector & dtoggle

- de1plus/profile.tcl
- de1plus/shot.tcl
- de1plus/vars.tcl
This refactors a couple of shot & profile commands to work on arbitrary files instead of being bound to the global settings or all shots at once. This is in preparation of the forthcoming version of DYE that allows users to export past shot files and to view profiles from past shots.
- New command `shot::convert_legacy_to_v2` converts just one file. Code is taken from `shot::convert_all_legacy_to_v2`, which has been refactored to use the new command on each history file, to avoid code duplicity.
- `profile::pressure_to_advanced_list`, `profile::flow_to_advanced_list`, and `profile::settings_to_advanced_list` get an optional argument `settingsvar` that specifies the global variable they should use. This allows to make the conversion of basic (flow/pressure) profiles to advanced profiles …
> Convert individual shots to v2 & profile basic to advanced with any array

- de1plus/utils.tcl
The screensaver doesn't read files that are not *.jpg (such as *.JPG), this makes the filetype in the lookup case insensitive.
> Makes screensaver file lookup case insensitive

- de1plus/dui.tcl
2 minor fixes in the recently added DUI widgets:
- `dui::add::dselector` coordinates were not calculated correctly when placed on dialog pages.
- add support for `-label` and `-label_*` set of options in `dui::add::dtoggle`
> DUI: Place dselectors correctly in dialogs, add dtoggle support for -label

- de1plus/profile.tcl
This adds new features to the `::profile` namespace and modifies a few things to make them more generic, so they can be used in the next version of the DYE Profile Viewer:
- New command `profile::read_legacy`, reads a legacy (.tcl) profile into an array. This is needed because the standard profile loading command is `load_settings_var`, which loads directly into the global `$::settings` variable, whereas the new command will restrict the read variables to those from profiles, and return the result as a list that can be set to an array.
- New command `profile::legacy_to_textual` transforms a legacy (.tcl) profile into a dictionary with a human-readable textual representation of the profile. This has been refactored from code in the DYE plugin so it can be easily reused by all skin & plugin …
> Profile read and textual

- de1plus/dui.tcl
- documentation/decent_user_interface.md
- DUI dbuttons gain an option `-tap_pad` to enlarge the "clickable area" around the visible button.
- The new larger area is used in DUI dcomboboxes drop-down arrow, as several users have reported that it was too small
- Buttons in DUI dialog pages get a sligthly larger tapping area.
- Debug mode for buttons (`dui config debug_buttons 1`) was not showing all clickable areas, also if the button was moved at runtime the debug rectangle outline wasn't moved. Both fixed now.
- DUI dselectors were not getting the "<main_tag>*" canvas tag, so they could not be referred to as a whole. Now fixed.
> New dbutton option -tap_pad. Button debug fixes. dselector tag fix.

- de1plus/profile.tcl
New and modified commands in the `::profile` namespace, continuing with the objective of providing a set of reusable commands to manage profiles that work on input and output data different of the `settings` global variable. All of this is needed for the forthcoming version of DYE.
- New command `profile::profile_type_text` returns an english textual description of the profile type that includes both `settings_profile_type` and `beverage_type` in one.
- New command `profile::find_file` returns the full path for an existing profile filename (both legacy and v2)
- New command `profile::modify_legacy` to easily modify parts of legacy profile files.
- New command `profile::import_legacy`, taken from DYE, handles importing legacy profiles from sources such as history shots or Visualizer …
> Legacy profile management commands

- de1plus/profile.tcl
Fixes in profile procs:
- Set variable `profile_filename` in read_legacy when src_type='profile_file'
- Fix bug in a log message in `modify_legacy` when the var being defined was undefined in the original profile file. This produced a runtime error when trying to modify the beverage type in the DYE Profile Viewer and it was not defined at all in the profile file.
Minor changes in DYE profile tools buttons and workflow:
- Profile Viewer and Profile Selector now each get its own icon in buttons.
- Added button to launch the Profile Selector also in basic profiles editors (only appeared in advanced)
- Removed the Profile Selector button that appeared wrongly in page `settings_2c2`
- New button on the Profile Selector to preview the selected profile in the Profile Viewer.
> Fix profile functions & DYE update

- de1plus/history_viewer.tcl
This modifies the colors of the graph series lines in the default history viewer DUI theme, to match those used in the Insight/default skins. Skins wanting to use other colors can redefine them in their own themes.
> Use Insight graph series colors in history viewer default DUI theme

- de1plus/profile.tcl
`profile::read_legacy` now always overwrites the `advanced_shot` variable of basic profiles if it is already defined in the file, to ensure its definition matches the basic profile variables in the GUI. 
This will avoid errors like the one in profile `Best overall pressure profile.tcl`, whose `advanced_shot` in the repo profile as of 2021-12-05 had nothing to do with the basic profile definition, as [reported by Richard Steeper](https://3.basecamp.com/3671212/buckets/7351439/messages/4141407262#__recording_4416261147).
> Always overwrite basic profiles' advanced_shot in profile::read_legacy

- de1plus/profile.tcl
The textual representation of profiles produced by `profile::legacy_to_textual` now does _not_ show the "Per-step temperatures enabled" message if the profile is advanced. Solves the problem reported by Richard Steeper.
> legacy_to_textual don't show "Per-step temps" text in non-basic profiles

- de1plus/bluetooth.tcl
This PR fixes `Error: invalid command name "ifexist"` error message.
This issue was also reported in Dicent forum.
https://3.basecamp.com/3671212/buckets/7351439/messages/4347747948#__recording_4521693300
> Fix typo "ifexist"

- de1plus/device_scale.tcl
- de1plus/machine.tcl
As discussed with @decentjohn at Diaspora [1] this PR adds an option to let scale timers only run, if an Espresso is made. So the duration of the last Espresso is always shown at the scale display, not matter if one flushed or steamed afterwards.
[1] https://3.basecamp.com/3671212/buckets/7351439/messages/4509014809
> introduce option to enable scales timer only for Espresso

- de1plus/profile.tcl
- Only include the "limiter ranges of action" text on the textual profiles if there is at least one step that has a pressure or flow limit. Before they were always shown.
- The "move-on-weight" profile variable `weight` was introduced in profiles after the legacy to v2 conversion was written, and never made to the converter. Added so that now this variable correctly appears on the JSON (v2) profiles.
> Fix profile textual limiters & add move-on-weight to v2

- de1plus/utils.tcl
Experienced this when battery was low. Updated the logs to use v2 to prevent crash:
Untrapped error running de1_ui_startup with result: can't read "::settings(battery_very_low_trigger)": no such element in array
2022-08-29 07:06:50.580 CRITICAL: -code 1 -level 0 -errorstack {INNER loadArrayStk CALL {check_battery_low 70} CALL {display_brightness 70} CALL {::page_onload {} off} UP 5 CALL {::dui::page::load off} CALL {page_display_change splash off} CALL run_de1_app CALL ui_startup CALL de1_ui_startup} -errorcode {TCL READ VARNAME} -errorinfo {can't read "::settings(battery_very_low_trigger)": no such element in array
2022-08-29 07:06:50.580 CRITICAL:     while executing
2022-08-29 07:06:50.580 CRITICAL: "msg -WARNING "Battery is very low ($percent < $::settings(battery_very_low_trigger)) …
> Updated logs to use v2

- de1plus/bluetooth.tcl
- de1plus/device_scale.tcl
Full write-up can be found [here](https://public.3.basecamp.com/p/opKQmZ9CJRorLkPU41wpbqwu)
Features:
- Increased tickle timeout to ensure we're actually disconnected before displaying to the user
- Completely revamped how we parse data on acaia:
- Scan the buffer to see if any data is viable.
- Throw away messages that don't have the correct msg or event type (fixes watchdog misfire)
- Added an arbitrary length threshold in case we do find a valid msg but the data is too long to care about (also fixes watchdog misfire/blips in weight graph)
- Added support for event type 11 to give us a greater chance of having valid data
> Acaia Lunar 2021 Fix [possibly others]

- de1plus/bluetooth.tcl
Support PEARL 2021 scales under the Acaia Pyxis profile, as well as PEARLS.
Pearl 2021 scales appear with the name `PEARL-{last3hex}`
I manually made this change and copied bluetooth.tcl over to my tablet using File Manager+, then tested with my Pearl 2021 scales.
The scales seem to be working correctly (https://visualizer.coffee/shots/e176dd5c-b744-4ea3-a4fd-1b8b6495213b).
> Support Acaia Pearl 2021 scales

- de1plus/bluetooth.tcl
- de1plus/device_scale.tcl
- de1plus/machine.tcl
Implementation of the DiFluid Microbalance, including auto-tare and timer.
When the scale connects the auto-notifications are enabled and it is set to report in grams.
Documentation can be found here: https://github.com/DiFluid/difluid-sdk-demo/blob/master/docs/protocolMicrobalance.md
The scale needs to run on Firmware Version 3.0.0+
> DiFluid Microbalance implementation

- de1plus/dui.tcl
This fixes the bugs spotted by @Damian-AU when developing the P&D skin.
- Now short presses shouldn't generate long presses under some circunstances, like before
- The default threshold to distinguish between short and long presses have been increased from 200 to 300 milliseconds
- `dbutton` widget gains a new argument `-longpress_threshold` that allows modifying the number of milliseconds to trigger a longpress event on every dbutton.
> Dui fix longpress

- de1plus/dui.tcl
Fixes symbol names changes in DUI (dialog closing cross, and arrows in DUI number editor) after the change to Font Awesome 6 names.
> Fix symbol changes in DUI

- de1plus/dui.tcl
A few minor DUI bug fixes that were pending:
1. Adding items already added to a page to another page using ``dui::page::add_items`` could make the items non-visible due to z-order problems. Fixed. Solves issue #282 
2. A possible fix for the problem of DUI longpresses of dbuttons in android, as described in issue #280. This seems to fix it on my tests but as the problem is hard to reproduce, I need @Damian-AU to check and verify.
3. ``dui::page::retheme`` would raise a runtime error due to an undefined-variable return value if the new_theme didn't exist, as reported by @decentjohn on issue #288, fixed.
4. DUI "round outline" dbutton corners now share a common tag suffix ``<main_tag>-out-cor`` so they can be modified at once. The straight lines in the outline also receive a new common tag …
> DUI fixes (z-order, longpress, retheme, dbutton corners)

- .gitmodules
This adds my MQTT plugin, so it can be present as part of the default install without users needing to manually copy it on to their tablet.  Here is the thread discussing the plugin: https://3.basecamp.com/3671212/buckets/7351439/messages/6317898181
If you prefer, I'm also fine with the MQTT plugin being moved directly into the de1app repository rather than being a submodule.  This would perhaps make it easier to be kept in sync with the de1app code if there are ever any changes to de1app code that require changes to the MQTT plugin.  I'm happy assigning copyright ownership as needed.
> Add mqtt plugin

- de1plus/bluetooth.tcl
Add support for reading the battery level of Felicita Arc bluetooth scale.
Rounds battery level to 10%, as I've seen it jumping from raw values `158` and `157` constantly and confirmed the same behavior in despresso. 
I believe 10% level change is precise enough for a scale.
> read felicita arc battery level

- de1plus/bluetooth.tcl
The BooKoo Scale does indeed report its battery level as well as a flow. While there is no place to plug in scale flow (for now) as an additional datapoint, we can prepare it by parsing and use the battery level as well for the app analog to the felicita and decent scale.
> scale, bookoo: Cleanup the code and add battery and flow parsing

- de1plus/bluetooth.tcl
- de1plus/machine.tcl
This PR fixes two bugs:
1. Negative weight values are now parsed properly from the payload
2. Use the correct service UUID channels for the scale
> Fix some Varia scale integration bugs

- de1plus/machine.tcl
This PR should fix the [error that was seen when trying to tare AKU scales](https://3.basecamp.com/3671212/buckets/7351439/messages/7090482794#__recording_8344601044).
> Fix Varia AKU tare issue

- de1plus/device_scale.tcl
These two commits are the most basic ones, I think we could also do increased weight, but I only have 1 scale, when I plotted all the times this worked out quite nicely.
> Improve starting estimate for DiFluid and avoid cross-scale contamination of period estimation

- de1plus/bluetooth.tcl
- de1plus/device_scale.tcl
Recent versions of AndroWish appear to have a bug in the "ble write" behavior: if the write type is not explicitly specified it now always performs the write using `WRITE_TYPE_DEFAULT` rather than the write type advertised by the device.
Older Acaia Lunar scales advertise their command characteristic as `WRITE_TYPE_NO_RESPONSE`, and reject the write with a permission denied error if you attempt to write using `WRITE_TYPE_DEFAULT`.  The problem is made worse by the fact that AndroWish currently does not pass write errors back to the tcl callback: this results in the tcl bluetooth write queue getting stuck since it never receives a callback indicating that the outstanding write finished.
This fixes the code by explicitly specifying the write type when performing writes to Acaia scales. …
> Scale: fix connectivity for older Acaia Lunar scales
